---
host :
  # 绑定域名
  - "localhost"
  - "127.0.0.1"
#是否为调试模式,发布前请关闭调试模式
debug : false
# 使用伪静态
rewrite: true
# 项目名
app : Vpay
# 项目升级次数
verCode : 65
# 项目版本名称
verName : 3.0
# 日志有效期(天)
logValidTime : 30
# 安装程序模块名
install : index/install/start
# admin用户目录
admin: "administrator"



