user:
  username : admin #用户名
  password : 'f6fdffe48c908deb0f4c3bd36c032e72' #加密密码
mail:
  smtp : ssl://smtp.exmail.qq.com #邮件服务器
  send : '' #邮件发送账户
  passwd : ''#邮件发送密码
  port : ''#邮件发送端口
  receive : ''#邮件接送者
  sendType: "1" # 0 不接收 1 用户发起支付（补单） 2 用户支付成功 4 收益日报 8 收益周报 16 Cookie失效 32 监控掉线
pay :
  validity_minute: 5
  alipay_private_key : '' # 支付宝的私钥
  alipay_public_key : '' # 支付宝的公钥
  alipay_id: ""
  alipay_notify: ""
  alipay_sign_type: ""
shop:
  name : "Ankioの杂货铺"
  state : 1
  notice : "欢迎来到Ankioの杂货铺！"
login: ""#采用集成登录框架进行登录

